### PR TITLE
Plymouth

### PR DESCRIPTION
**Pull request by hellnest**
Please recheck the builders and hook, :) I took it from mkinitcpio hook :)

### CODE REVIEW

**Comment by falconindy** [comment]
Please test your work before submitting a pull request. &> isn't valid /bin/sh.

**Comment by hellnest** [comment]
Oke, i will take a test to make it play nice with systemd. :) i'm still figuring out how to enable it with systemd since it's always failed

**Comment by falconindy** [comment]
There's a lot more to making a plymouth hook as well. There's various libraries that need to be included as well as /etc/passwd. I have files at work I can post for you if you want to see if they can be ported to geninit (I had it working with mkinitcpio and systemd, purely out of curiousity).

**Comment by hellnest** [comment]
Mkinitcpio is working on mine. Can you show me your systemd plymouth? I really don't understand about which services that needed. For geninit i know i should add more file and binary to make plymouth work and i guess i already figure it out. But for systemd i'm still can't find how to make it. I take a look into fedora systemd units but still not understand that well.

**Comment by falconindy** [comment]
Looks like I deleted the hooks I had that were working with systemd. I can't say I have the time and interest to figure out what I did, again.

**Pull request closed without merging**
